# GitHub Actions workflow that builds the book and uploads to gh-pages
name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.10"
          miniforge-variant: Mambaforge
          use-mamba: true
          channels: conda-forge,defaults
          environment-file: environment.yml

      - name: Build the website
        run: jupyter-book build .

      - name: Push to gh-pages
        if: success() && github.event_name == 'push'
        # Don't use tags: https://julienrenaux.fr/2019/12/20/github-actions-security-risk/
        uses: peaceiris/actions-gh-pages@8a36f3edfc5d1cbae6b09e6f5a7d7b19e5b7a73b
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/html
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
